apiVersion: apps/v1
kind: Deployment
metadata:
  name: moba-socketio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moba-socketio-app
  template:
    metadata:
      labels:
        app: moba-socketio-app
    spec:
      containers:
        - name: moba-socketio-app
          image: fittipaldi/moba-socketio-app:latest  # Ensure correct tag
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
