apiVersion: v1
kind: Service
metadata:
  name: moba-socketio-app-service  # Your desired service name
spec:
  selector:
    app: moba-socketio  # Ensure this matches your Pod's labels
  ports:
    - protocol: TCP
      port: 4000        # The port inside the cluster
      targetPort: 4000  # Your app’s container port
      nodePort: 30001   # External port (must be in range 30000-32767)
  type: NodePort
