apiVersion: v1
kind: Service
metadata:
  name: moba-socketio-app-service
spec:
  type: NodePort  # LoadBalancer support
  ports:
    - port: 4000        # External port of the service
      targetPort: 4000   # Port inside the container
      nodePort: 30001   # The NodePort you want to expose (you can change)
  selector:
    app: moba-socketio-app-service
