apiVersion: v1
kind: Service
metadata:
  name: moba-socketio-app-service
spec:
  selector:
    app: moba-socketio-app
  ports:
    - protocol: TCP
      port: 4000      # External port of the service
      targetPort: 4000  # Port inside the container
      nodePort: 30001  # The NodePort you want to expose (optional)
  type: NodePort
