apiVersion: v1
kind: Service
metadata:
  name: moba-socketio-app-service
spec:
  selector:
    app: moba-socketio-app
  ports:
    - protocol: TCP
      port: 4000        # External port
      targetPort: 4000  # Internal container port
  type: NodePort
